[general]
import = ["/home/jsmith/.config/alacritty/themes/themes/tokyo_night_storm.toml"]    

[font]
size = 15.0 # 15" 
#size = 20.0  # 24" 

[font.normal]
family = "AdwaitaMono Nerd Font"

[window]
padding.x = 4
padding.y = 4
