[general]
import = ["/home/jsmith/.config/alacritty/themes/themes/alabaster_dark.toml"]    

[font]
size = 19.0 # 15" 

[font.normal]
# family = "AdwaitaMono Nerd Font"
family = "MesloLGS Nerd Font"
style = "Bold"

[window]
padding.x = 10
padding.y = 10
